### ISSUE TITLE
sum_squares doesn't work in R 3.5.2

### ISSUE THREAD

**Issue by dosaaaai** [anqif/CVXR#44] opened 2019-03-18 02:56 UTC
Hi, 
Thank you so much for building this package. 

I am using R 3.5.2 64-bit with CVXR_0.99-3 on windows ten enterprise. CVXR_0.99-3. The _sum_squares_ function in the objective function used for codes in the[ link](https://cvxr.rbind.io/cvxr_examples/cvxr_gentle-intro/) lead me to in-feasibility, however, if I manually code the the sum of squares the problem is optimal. 

For instance in 'simple examples' /Ordinary Least Squares section in the above link, if we use 
`objective <- Minimize(sum_squares(y - X %*% beta))`
 $status
[1] "infeasible_inaccurate"

$`11`
[1] NA

$value
[1] Inf

$solver
[1] "ECOS"

$solve_time
[1] 0.780979

$setup_time
[1] 0.01354082

$num_iters
[1] 100

$getValue
function (objet) 
{
    if (is(objet, "Variable") || is(objet, "Constraint")) {
        return(result[[as.character(id(objet))]])
    }
    if (is_zero(objet)) {
        size <- size(objet)
        valResult <- matrix(0, nrow = size[1], ncol = size[2])
    }
    else {
        arg_values <- list()
        idx <- 1
        for (arg in objet@args) {
            arg_val <- if (is_constant(arg)) {
                value(arg)
            }
            else {
                getValue(arg)
            }
            if (is.null(arg_val) || (any(is.na(arg_val)) && !is_constant(objet))) 
                return(NA)
            else {
                arg_values[[idx]] <- arg_val
                idx <- idx + 1
            }
        }
        valResult <- to_numeric(objet, arg_values)
    }
    if (all(intf_size(valResult) == c(1, 1))) 
        intf_scalar_value(valResult)
    else valResult
}
<bytecode: 0x0000000015286ea8>
<environment: 0x000000001525f250>

$getDualValue
function (objet) 
{
    if (!is(objet, "Constraint")) {
        stop("getDualValue: argument should be a Constraint!")
    }
    getValue(objet)
}
<bytecode: 0x0000000015285b58>
<environment: 0x000000001525f250>

`objective <- Minimize(sum((y - X %*% beta)^2)) `
$status
[1] "optimal"

$value
[1] 9946.64

$`11`
             [,1]
 [1,]  0.01490596
 [2,]  0.74633566
 [3,] -0.04689927
 [4,]  1.06782714
 [5,]  0.19997118
 [6,]  0.03308453
 [7,]  0.43790907
 [8,]  1.08405414
 [9,]  0.01644479
[10,]  0.67748525

$solver
[1] "ECOS"

$solve_time
[1] 0.656408

$setup_time
[1] 0.03219767

$num_iters
[1] 16

$getValue
function (objet) 
{
    if (is(objet, "Variable") || is(objet, "Constraint")) {
        return(result[[as.character(id(objet))]])
    }
    if (is_zero(objet)) {
        size <- size(objet)
        valResult <- matrix(0, nrow = size[1], ncol = size[2])
    }
    else {
        arg_values <- list()
        idx <- 1
        for (arg in objet@args) {
            arg_val <- if (is_constant(arg)) {
                value(arg)
            }
            else {
                getValue(arg)
            }
            if (is.null(arg_val) || (any(is.na(arg_val)) && !is_constant(objet))) 
                return(NA)
            else {
                arg_values[[idx]] <- arg_val
                idx <- idx + 1
            }
        }
        valResult <- to_numeric(objet, arg_values)
    }
    if (all(intf_size(valResult) == c(1, 1))) 
        intf_scalar_value(valResult)
    else valResult
}
<bytecode: 0x0000000015286ea8>
<environment: 0x000000002203dbb0>

$getDualValue
function (objet) 
{
    if (!is(objet, "Constraint")) {
        stop("getDualValue: argument should be a Constraint!")
    }
    getValue(objet)
}
<bytecode: 0x0000000015285b58>
<environment: 0x000000002203dbb0>

$delta
Variable(10, 1)

**Comment by bnaras** [comment] 2019-03-18 17:30
Unable to reproduce this error, so will close this issue.  If you still think there is an issue, do provide a reprex. 

Attached is a run using the current versions. 

[gentle.zip](https://github.com/anqif/CVXR/files/2979452/gentle.zip)

**Closed by bnaras** 2019-03-18 17:30 UTC
